---
title: "model"
author: "Yuxuan Ke"
date: "2023-10-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(conleyreg)
library(ivreg)
library(fixest)
```

## baseline model

```{r}
data = read.csv("data/final_dta_data.csv")
op.data = data %>% filter(!is.na(ocean_prd))
```

```{r}
conflict 
conflict50nmi 
conflict100nmi 
conflict150nmi 
conflict200nmi 
fatalities 
catch000 
indcatch000 
nidcatch000 
iuu000 
ind_iuu000 
nid_iuu000 
ocean_prd
```

Note: Heteroskedasticity and autocorrelation consistent (HAC) covariance matrix for the error term can account for some heteroskedasticity and autocorrelation that might accur in spatial data.

`fixest` tutorial: https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html#3_Instrumental_variables


### Table 3 and part of Table 4
```{r}
prov = paste0("prodummy", 1:34)
dvar = "conflict100nmi"
indvar = "indcatch000"
iv = "ocean_prd"

fml = as.formula(paste(indvar, paste(iv, paste(prov, collapse=" + "), sep = "|"), sep=" ~ "))
fit.1stg = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #ols
summary(fit.1stg)
fitstat(fit.1stg, type = "wf") # F-test

#summary(lm(fml, data = op.data))


#fml = as.formula(paste(dvar, paste(paste(indvars, collapse=" + "), paste(iv, collapse=" + "), sep = "|"), sep=" ~ "))
fml = as.formula(paste(dvar, paste(paste( paste(prov, collapse="+"), indvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
fitstat(fit.iv, type = "kpr") # KP test
```

```{r}
dvar = "conflict100nmi"
indvar = "nidcatch000"
iv = "ocean_prd"

fml = as.formula(paste(indvar, paste(iv, paste(prov, collapse=" + "), sep = "|"), sep=" ~ "))
fit.1stg = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #ols
summary(fit.1stg)
fitstat(fit.1stg, type = "wf") # F-test

#summary(lm(fml, data = op.data))


#fml = as.formula(paste(dvar, paste(paste(indvars, collapse=" + "), paste(iv, collapse=" + "), sep = "|"), sep=" ~ "))
fml = as.formula(paste(dvar, paste(paste( paste(prov, collapse="+"), indvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
fitstat(fit.iv, type = "kpr") # KP test
```

```{r}
dvar = "conflict100nmi"
indvar = "catch000"
iv = "ocean_prd"

fml = as.formula(paste(indvar, paste(iv, paste(prov, collapse=" + "), sep = "|"), sep=" ~ "))
fit.1stg = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #ols
summary(fit.1stg)
fitstat(fit.1stg, type = "wf") # F-test

#summary(lm(fml, data = op.data))


#fml = as.formula(paste(dvar, paste(paste(indvars, collapse=" + "), paste(iv, collapse=" + "), sep = "|"), sep=" ~ "))
fml = as.formula(paste(dvar, paste(paste( paste(prov, collapse="+"), indvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
fitstat(fit.iv, type = "kpr") # KP test
```

### Table 4 (rest)

```{r}
# OLS
dvar = "conflict100nmi"

# (1)
indvar = "indcatch000"
fml = as.formula(paste(dvar, indvar, sep=" ~ "))
fit.ols = feols(fml, data = data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical"))
summary(fit.ols)

# (2)
indvar = "nidcatch000"
fml = as.formula(paste(dvar, indvar, sep=" ~ "))
fit.ols = feols(fml, data = data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical"))
summary(fit.ols)

# (3)
indvar = "catch000"
fml = as.formula(paste(dvar, indvar, sep=" ~ "))
fit.ols = feols(fml, data = data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical"))
summary(fit.ols)
```
```{r}
# Pooled 2SLS
dvar = "conflict100nmi"
iv = "ocean_prd"

# (4)
endvar = "indcatch000"
fml = as.formula(paste(dvar, paste(1, paste(endvar, iv, sep = "~"), sep = "|"), sep=" ~ "))
fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)

# (5)
endvar = "nidcatch000"
fml = as.formula(paste(dvar, paste(1, paste(endvar, iv, sep = "~"), sep = "|"), sep=" ~ "))
fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)

# (6)
endvar = "catch000"
fml = as.formula(paste(dvar, paste(1, paste(endvar, iv, sep = "~"), sep = "|"), sep=" ~ "))
fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

```{r}
# FIxed effects 2SLS

# (10)
prov = paste0("prodummy", 1:34)
dvar = "fatalities100nmi"
indvar = "catch000"
iv = "ocean_prd"

fml = as.formula(paste(dvar, paste(paste( paste(prov, collapse="+"), indvar, sep = "|"), iv, sep = "~"), sep=" ~ "))
fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```


## conflict model
### Table 8
```{r}
dvar = "conflict2016"
covar = c("conflict100nmi", prov)
endvar = "indcatch000"
iv = "ocean_prd"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

```{r}
endvar = "nidcatch000"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

```{r}
endvar = "catch000"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

### Table 10
```{r}
dvar = "protest_count100nmi"
covar = c(prov)
endvar = "catch000"
iv = "ocean_prd"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

```{r}
dvar = "civilian_count100nmi"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

```{r}
dvar = "battle_count100nmi"

fml = as.formula(paste(dvar, paste(paste(paste(covar, collapse="+"), endvar, sep = "|"), iv, sep = "~"), sep=" ~ "))

fit.iv = feols(fml, data = op.data, vcov = vcov_conley(lat = "latitude", lon = "longitude", 
                                       cutoff = 111, distance = "spherical")) #2sls
summary(fit.iv)
```

