---
title: "Sahana's playground"
author: "Sahana Rayan"
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries


```{r}
# install.packages("fixest")
library(fixest)
library(tidyverse)
```

# Loading data set

```{r}
final_data <- read_csv("../data/final_dta_data.csv")
```


# Preprocessing to get the province data


# ```{r}
# dummy_vars_final <- final_data[, 36:69]
# # dummy_vars_final[, 1] <- ifelse(dummy_vars_final[, 1] == 1, colnames(dummy_vars_final)[1], "")
# 
# undummied <- 1:34 |> map(\(num) ifelse(dummy_vars_final[, num] == 1, num, 0))
# undummied <- data.frame(undummied) %>% 
#   mutate(finallabel = select(., starts_with("pro")) %>% rowSums())
# final_data$province <- undummied$finallabel
# ```





```{r}
first_stage_model_ic <- lm(indcatch000 ~ ocean_prd | prodummy1 + prodummy2 + prodummy3 + prodummy4 +
                           prodummy5 + prodummy6 + prodummy7 + prodummy8 + prodummy9 + prodummy10
                           + prodummy11 + prodummy12 + prodummy13 + prodummy14 + prodummy15 + prodummy16
                           + prodummy17 + prodummy18 + prodummy19 + prodummy20 + prodummy21
                           + prodummy22 + prodummy23 + prodummy24 + prodummy25 + prodummy26
                           + prodummy27 + prodummy28 + prodummy29 + prodummy30 + prodummy31
                           + prodummy32 + prodummy33 + prodummy34, data = final_data)
summary(first_stage_model_ic)
```

##

```{r}
prodummy_part_form <- paste0(paste("prodummy", 1:34, sep = ""), collapse= " + ")
feols_model_ic <- feols(formula(paste("indcatch000 ~ ocean_prd |" ,prodummy_part_form )),
                        data = final_data)
feols_model_ic_2 <- feols(formula(paste("conflict100nmi ~ 1 |", prodummy_part_form, "|",
                                        "indcatch000 ~ ocean_prd")),
                        data = final_data)
cov <- vcov_conley(feols_model_ic, cutoff = "115mi")
cov
```

```{r}
print(summary(feols_model_ic_2, stage = 1))
print("\n")
print(summary(feols_model_ic))
fitstat(feols_model_ic_2, type = "kpr")
```
There is some weirdness with the KP stat


```{r}
prov = paste0("prodummy", 1:34)
dvar = "conflict100nmi"
indvar = "indcatch000"
iv = "ocean_prd"

fml = as.formula(paste(indvar, paste(iv, paste(prov, collapse=" + "), sep = "|"), sep=" ~ "))
print(fml)
fml = as.formula(paste(dvar, paste(paste( paste(prov, collapse="+"), indvar, sep = "|"), iv, sep = "~"), sep=" ~ "))
print(fml)
```

```{r}
summary(feols_model_ic)
```



```{r}

# f statistic test
fitstat(feols_model_ic, type = "ivf")

# kpr test?
fitstat(feols_model_ic, type= "kpr")

```


